### ISSUE TITLE
你又在写些奇怪的东西了

### ISSUE THREAD

**Issue by ice1000** [Predator-SD/ObjAn#1]
还有你为啥老是星自己的项目 :kissing_closed_eyes:

**Comment by Predator-SD** [comment]
233~我想做个生命线 @ice1000

**Comment by ice1000** [comment]
生命线啥玩意？ :disappointed:

**Comment by Predator-SD** [comment]
一个实时互动文字冒险游戏

**Comment by ice1000** [comment]
哦哦哦 是不是类似我的城堡游戏那种 :joy:

**Comment by Predator-SD** [comment]
并不是，是实时的，你自己玩玩生命线吧

**Comment by ice1000** [comment]
。。。。你这玩意如何运行？ :joy:

**Comment by Predator-SD** [comment]
用python直接运行Tales.py，剧本在Data里，就是那个Tale.json，存档是status.json
@ice1000

**Comment by ice1000** [comment]
好的 我clone下来看看 顺便推荐一个屁眼的IDE：[PyCharm](https://www.jetbrains.com/pycharm) 简直神器

**Comment by Predator-SD** [comment]
嗯，有mac版吗

**Comment by ice1000** [comment]
肯定有啊 :joy: Java写的东西怎么可能不跨平台呢

**Comment by ice1000** [comment]
传教成功 close issue
